# fly.toml app configuration file generated for pgautositemap on 2025-09-25T16:29:18+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pgautositemap'
primary_region = 'nrt'
kill_signal = 'SIGINT'
kill_timeout = '10s'

[experimental]
  auto_rollback = true

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 256
